[project]
name = "code-practise"
version = "0.1.0"
description = "Code practise using PySide6"
readme = "README.md"
requires-python = ">=3.14,<3.15"
dependencies = [
    "pyside6>=6.11.2,<6.12",
]

[project.scripts]
code-practise = "code_practise.app:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.4",
]

[tool.ruff]
line-length = 88
target-version = "py314"

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "C90"]

[tool.ruff.lint.mccabe]
max-complexity = 10
